# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.provider "docker" do |d|
    d.vagrant_vagrantfile = "../proxyVM/Vagrantfile"
    d.build_dir = "."
  end
end
