# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 9300, host: 9300
  config.vm.provider "docker" do |d|
    d.vagrant_vagrantfile = "../proxyVM/Vagrantfile"
    d.build_dir = "."
  end
end
